### ISSUE TITLE
How to specify symlink in goal.yml

### ISSUE THREAD

**Issue by jomonkj** [hiqdev/hidev#5]

**Comment by jomonkj** [comment]
not possible?

**Comment by hiqsol** [comment]
Possible. Sorry for the long answer.
There is no exact aliasing yet.
But you can use: `before` and `after` features.
See: https://github.com/hiqdev/hidev-php/blob/master/src/config/goals.yml#L1

E.g. `hidev build` runs `hidev fix` and if it finishes without error then runs `hidev test`

**Comment by jomonkj** [comment]
can i do it like
```yml
adminApp:
  path: .
  public:
    admin:
      LINK_NAME:
        link: TARGET
```
